USE PRD_DATA_VAULT;

DROP TABLE IF EXISTS "PRD_INFO_MART_OTC"."TRANSACTION_ARB_CALC";

CREATE TABLE "PRD_INFO_MART_OTC"."TRANSACTION_ARB_CALC"
(
		FISCAL_YEAR 					VARCHAR(30),
        FISCAL_QUARTER 					VARCHAR(30),
        FISCAL_QUARTER_START_DATE 		DATE,
        FISCAL_QUARTER_END_DATE 		DATE,
	    TRANS_SF_OPPORTUNITY 			VARCHAR(1300),
	    END_USER_NAME 					VARCHAR(1300), 
	   	OPP_ACCOUNT_ID 					VARCHAR(1300), 
	    OPPORTUNITY_ID					VARCHAR(1300),
	   	OPP_TYPE						VARCHAR(1300),
	    OPPORTUNITY_NAME				VARCHAR(1300), 
	    OPP_OWNER_NAME					VARCHAR(1300),
	    TRANSACTION_TYPE				VARCHAR(100), 
	    PO_NUMBER						VARCHAR(1300), 
	    TRANDATE						DATE, 
	    TRANID							VARCHAR(1300),
	    TRANSACTION_ID					VARCHAR(100),
	    TRANSACTION_LINE_ID				VARCHAR(100),
  		ITEM_KEY						VARCHAR(100),
  		PRODUCT_KEY						VARCHAR(100),
  		ITEM_ID							VARCHAR(100),
  		SFDC_PRODUCT_ID					VARCHAR(100),
  		SUBTYPE							VARCHAR(100),
  		TYPE_NAME						VARCHAR(100),
  		SAAS_PRODUCT_FAMILY				VARCHAR(100),
	    ITEM_FULL_NAME					VARCHAR(1300), 
	    ITEM_SALES_DESCRIPTION			VARCHAR(1300),
	    PRIMARY_USE_CASE				VARCHAR(1300),
	    SECONDARY_USE_CASES				VARCHAR(1300),
	    PRODUCT_FAMILY					VARCHAR(1300),
	    PRODUCT_FAMILY_SUBTYPE_NAME		VARCHAR(1300),
	    PRODUCT_CATEGORY				VARCHAR(1300),
	    SUB_RENEWAL						VARCHAR(1300),
	    SUPPOSED_TO_BE_SUB_RENEWAL		VARCHAR(1300),
	    CHART_OF_ACCOUNT_FULL_NAME		VARCHAR(1300),
	    CHART_OF_ACCOUNTS_TYPE_NAME		VARCHAR(1300),
	    LEGACY_TERM_START_DATE			DATE,
	    LEGACY_TERM_END_DATE			DATE,
	    AMOUNT_FOREIGN					NUMBER(30,15),
  		ARB_FLAG						VARCHAR(3),
  		ROUNDED_LEGACY_TERMS_MONTHS		NUMBER(10),
  		ROUNDED_LEGACY_TERMS_QUARTERS	NUMBER(10),
  		AMOUNT_CHANGE					VARCHAR(3),
  		SW_PERCENT						NUMBER(30,15),
  		NEW_SW_SUPPORT					NUMBER(30,15),
  		NEW_AMOUNT						NUMBER(30,15),
  		MULTI_YEAR						VARCHAR(3),
  		ARB_AMOUNT						NUMBER(30,15)
)
CLUSTER BY (FISCAL_QUARTER_END_DATE)
;

