CREATE OR REPLACE VIEW PRD_DATA_VAULT.PRD_INFO_MART_OTC.VW_TRANSACTION_ARB_ANNIVERSARY_SPLIT
AS
WITH CTE_SPLIT_ARR_CONFIG AS
(
	SELECT 
		T.RN AS SPLIT_ID,
		CASE 
			WHEN T.RN = 2  THEN '12'
			WHEN T.RN = 3  THEN '12,12'
			WHEN T.RN = 4  THEN '12,12,12'
			WHEN T.RN = 5  THEN '12,12,12,12'
			WHEN T.RN = 6  THEN '12,12,12,12,12'
			WHEN T.RN = 7  THEN '12,12,12,12,12,12'
			WHEN T.RN = 8  THEN '12,12,12,12,12,12,12'
			WHEN T.RN = 9  THEN '12,12,12,12,12,12,12,12'
			WHEN T.RN = 10 THEN '12,12,12,12,12,12,12,12,12'
		END AS SPLIT_ARR,
		CASE 
			WHEN T.RN = 2  THEN '2'
			WHEN T.RN = 3  THEN '2,3'
			WHEN T.RN = 4  THEN '2,3,4'
			WHEN T.RN = 5  THEN '2,3,4,5'
			WHEN T.RN = 6  THEN '2,3,4,5,6'
			WHEN T.RN = 7  THEN '2,3,4,5,6,7'
			WHEN T.RN = 8  THEN '2,3,4,5,6,7,8'
			WHEN T.RN = 9  THEN '2,3,4,5,6,7,8,9'
			WHEN T.RN = 10 THEN '2,3,4,5,6,7,8,9,10'
		END AS SPLIT_ARR_RANK
	FROM
	(
		SELECT  seq4(),ROW_NUMBER() OVER(ORDER BY seq4() ASC) RN
		FROM TABLE(generator(rowcount => 10)) v 
	) T
)
,CTE_NO_OF_SPLITS AS
(
	SELECT
		P.INP_NUMBER,
		P.REMAINDER,
		P.NO_OF_SPLITS,
		CASE 
			WHEN P.NO_OF_SPLITS = 1 THEN CAST(P.REMAINDER AS VARCHAR(10))
			WHEN P.REMAINDER = 0 THEN ARR.SPLIT_ARR||',12'
			ELSE ARR.SPLIT_ARR||','||P.REMAINDER 
		END AS SPLIT_ARR,
		CASE 
			WHEN P.NO_OF_SPLITS = 1 THEN '1'
			ELSE '1,'||ARR.SPLIT_ARR_RANK
		END AS SPLIT_ARR_RANK
	FROM
	(
		SELECT 
			T.RN 		 AS INP_NUMBER,
			MOD(T.RN,12) AS REMAINDER,
			CASE 
				WHEN MOD(T.RN,12) > 0 THEN FLOOR(T.RN/12)+1 
				WHEN MOD(T.RN,12) = 0 THEN FLOOR(T.RN/12)
			END AS NO_OF_SPLITS
		FROM
		(
			SELECT  seq4(),ROW_NUMBER() OVER(ORDER BY seq4() ASC) RN
			FROM TABLE(generator(rowcount => 100)) v 
		) T
	) P
	INNER JOIN CTE_SPLIT_ARR_CONFIG ARR
	ON (P.NO_OF_SPLITS = ARR.SPLIT_ID)
)
,CTE_SPLIT_ARR_ROW AS 
(
	SELECT 
		INP_NUMBER, 
		REMAINDER,
		NO_OF_SPLITS,
        SPLIT_ARR,
        SPLIT_ARR_RANK,
		SPLT_RANK.value :: INTEGER AS SPLT_RANK_INDEX
	FROM CTE_NO_OF_SPLITS,
    LATERAL FLATTEN(INPUT=>SPLIT(SPLIT_ARR_RANK,',')) SPLT_RANK
)
-- ARR Transactions Exploded to Apportion across Multiple Year Same Quarter Based on Contract Periods
-- ANNIVERSARY_FLAG Calculated Based On Contract Period exluding year 1 and Multi Year Flag
,CTE_SPLIT_ARR_FY_QTR AS
(
  SELECT 
      CURR_FY_QRTR.FISCAL_YEAR,
      CURR_FY_QRTR.FISCAL_QUARTER,
      CURR_FY_QRTR.FISCAL_QUARTER_START_DATE,
      CURR_FY_QRTR.FISCAL_QUARTER_END_DATE,
      'FY'||CAST(LPAD(TO_NUMBER(SUBSTRING(CURR_FY_QRTR.FISCAL_YEAR,3,2))+CURR_FY_QRTR.RN-1,2,'0') AS VARCHAR(2))            AS FISCAL_YEAR_SPLIT,
      CAST(
        TO_NUMBER(SUBSTRING(CURR_FY_QRTR.FISCAL_QUARTER,1,4))+CURR_FY_QRTR.RN-1 AS VARCHAR(4))
        ||
        '-'
        ||SUBSTRING(CURR_FY_QRTR.FISCAL_QUARTER,6,2)                                                                        AS FISCAL_QUARTER_SPLIT,
      DATEADD(year,CURR_FY_QRTR.RN-1,CURR_FY_QRTR.FISCAL_QUARTER_START_DATE)                                                AS FISCAL_QUARTER_START_DATE_SPLIT,
      DATEADD(year,CURR_FY_QRTR.RN-1,CURR_FY_QRTR.FISCAL_QUARTER_END_DATE)                                                  AS FISCAL_QUARTER_END_DATE_SPLIT,
      CURR_FY_QRTR.TRANSACTION_ID,
      CURR_FY_QRTR.TRANSACTION_LINE_ID,
      CURR_FY_QRTR.PO_NUMBER,
      CURR_FY_QRTR.TRANDATE,
      CURR_FY_QRTR.TRANSACTION_TYPE,
      CURR_FY_QRTR.TRANS_SF_OPPORTUNITY,
      CURR_FY_QRTR.OPP_ACCOUNT_ID,
      CURR_FY_QRTR.NAME,
      CURR_FY_QRTR.INDUSTRY,
      CURR_FY_QRTR.INDUSTRY_NEW,
      CURR_FY_QRTR.ACCOUNT_GEO,
      CURR_FY_QRTR.ACCOUNT_SEGMENT,
      CURR_FY_QRTR.ITEM_KEY,
      CURR_FY_QRTR.PRODUCT_KEY,
      CURR_FY_QRTR.ITEM_ID,
      CURR_FY_QRTR.SFDC_PRODUCT_ID,
      CURR_FY_QRTR.SUBTYPE,
      CURR_FY_QRTR.TYPE_NAME,
      CURR_FY_QRTR.SAAS_PRODUCT_FAMILY,
      CURR_FY_QRTR.ITEM_FULL_NAME, 
	  CURR_FY_QRTR.ITEM_SALES_DESCRIPTION,
	  CURR_FY_QRTR.PRIMARY_USE_CASE,
	  CURR_FY_QRTR.SECONDARY_USE_CASES,
	  CURR_FY_QRTR.PRODUCT_FAMILY,
	  CURR_FY_QRTR.PRODUCT_FAMILY_SUBTYPE_NAME,
	  CURR_FY_QRTR.PRODUCT_CATEGORY,
	  CURR_FY_QRTR.SUB_RENEWAL,
	  CURR_FY_QRTR.SUPPOSED_TO_BE_SUB_RENEWAL,
      CURR_FY_QRTR.LEGACY_TERM_START_DATE,
      CURR_FY_QRTR.LEGACY_TERM_END_DATE,
      CURR_FY_QRTR.AMOUNT_FOREIGN,
      CURR_FY_QRTR.ROUNDED_LEGACY_TERMS_MONTHS,
      CURR_FY_QRTR.ROUNDED_LEGACY_TERMS_QUARTERS,
      CURR_FY_QRTR.SW_PERCENT,
      CURR_FY_QRTR.NEW_AMOUNT,
      CURR_FY_QRTR.MULTI_YEAR,
      CURR_FY_QRTR.ARB_AMOUNT,
      CURR_FY_QRTR.NO_OF_SPLITS,
      CURR_FY_QRTR.SPLIT_ARR,
      CURR_FY_QRTR.RN,
      CASE
          -- If either No Legacy Term Start Date and Legacy Term End Date is NULL
          WHEN CURR_FY_QRTR.ROUNDED_LEGACY_TERMS_MONTHS IS NULL 
              THEN CURR_FY_QRTR.ARB_AMOUNT
          -- Contract is For less than 1 year
          WHEN CURR_FY_QRTR.ROUNDED_LEGACY_TERMS_MONTHS < 12 
              THEN CURR_FY_QRTR.ARB_AMOUNT
          -- Contract is For exactly 1 year
          WHEN CURR_FY_QRTR.ROUNDED_LEGACY_TERMS_MONTHS = 12 
              THEN CURR_FY_QRTR.ARB_AMOUNT
          -- Contract is For exactly n years / multiple pf 12 months (12,24,36,48,60 .... )
          WHEN MOD(CURR_FY_QRTR.ROUNDED_LEGACY_TERMS_MONTHS,12) = 0 
              THEN CURR_FY_QRTR.ARB_AMOUNT
          -- Contract is For more than 1 year (12 months) and Transaction Line is not the last line so ARB_AMOUNT will be billed
          WHEN CURR_FY_QRTR.ROUNDED_LEGACY_TERMS_MONTHS > 12 AND CURR_FY_QRTR.NO_OF_SPLITS > 1 AND CURR_FY_QRTR.RN < CURR_FY_QRTR.NO_OF_SPLITS 
              THEN CURR_FY_QRTR.ARB_AMOUNT
          -- Contract is For more than 1 year (12 months) and Transaction Line is the last line 
          --so ARB_AMOUNT will be the remaining from NEW_AMOUNT and no of full year Contract has been made
          WHEN CURR_FY_QRTR.ROUNDED_LEGACY_TERMS_MONTHS > 12 AND CURR_FY_QRTR.NO_OF_SPLITS > 1 AND CURR_FY_QRTR.RN = CURR_FY_QRTR.NO_OF_SPLITS
              THEN (CURR_FY_QRTR.NEW_AMOUNT - (CURR_FY_QRTR.ARB_AMOUNT * (CURR_FY_QRTR.RN - 1) ))
      END AS ARB_AMOUNT_UPDATED,
      CASE
          WHEN CURR_FY_QRTR.ROUNDED_LEGACY_TERMS_MONTHS IS NULL 
          THEN 'Year 1'
          WHEN CURR_FY_QRTR.ROUNDED_LEGACY_TERMS_MONTHS <= 12
          THEN 'Year 1'
          WHEN CURR_FY_QRTR.ROUNDED_LEGACY_TERMS_MONTHS > 12 AND CURR_FY_QRTR.RN = 1
          THEN 'Year 1'
          WHEN CURR_FY_QRTR.ROUNDED_LEGACY_TERMS_MONTHS > 12 AND CURR_FY_QRTR.RN > 1
          THEN 'Anniversary'
      END AS ANNIVERSARY_FLAG
  FROM
  (
      SELECT 
          CURR_FY_QRTR.FISCAL_YEAR,
          CURR_FY_QRTR.FISCAL_QUARTER,
          CURR_FY_QRTR.FISCAL_QUARTER_START_DATE,
          CURR_FY_QRTR.FISCAL_QUARTER_END_DATE,
          CURR_FY_QRTR.TRANSACTION_ID,
          CURR_FY_QRTR.TRANSACTION_LINE_ID,
          CURR_FY_QRTR.PO_NUMBER,
          CURR_FY_QRTR.TRANDATE,
          CURR_FY_QRTR.TRANSACTION_TYPE,
          CURR_FY_QRTR.TRANS_SF_OPPORTUNITY,
          CURR_FY_QRTR.OPP_ACCOUNT_ID,
          ACCOUNT_DIM.NAME,
          ACCOUNT_DIM.INDUSTRY,
          ACCOUNT_DIM.INDUSTRY_NEW,
          ACCOUNT_DIM.ACCOUNT_GEO,
          ACCOUNT_DIM.ACCOUNT_SEGMENT,
          CURR_FY_QRTR.LEGACY_TERM_START_DATE,
          CURR_FY_QRTR.LEGACY_TERM_END_DATE,
          CURR_FY_QRTR.AMOUNT_FOREIGN,
          CURR_FY_QRTR.ROUNDED_LEGACY_TERMS_MONTHS,
          CURR_FY_QRTR.ROUNDED_LEGACY_TERMS_QUARTERS,
          CURR_FY_QRTR.SW_PERCENT,
          CURR_FY_QRTR.NEW_AMOUNT,
          CURR_FY_QRTR.MULTI_YEAR,
          CURR_FY_QRTR.ARB_AMOUNT,
          CURR_FY_QRTR.ITEM_KEY,
          CURR_FY_QRTR.PRODUCT_KEY,
          CURR_FY_QRTR.ITEM_ID,
          CURR_FY_QRTR.SFDC_PRODUCT_ID,
          CURR_FY_QRTR.SUBTYPE,
          CURR_FY_QRTR.TYPE_NAME,
          CURR_FY_QRTR.SAAS_PRODUCT_FAMILY,
          CURR_FY_QRTR.ITEM_FULL_NAME, 
	      CURR_FY_QRTR.ITEM_SALES_DESCRIPTION,
	      CURR_FY_QRTR.PRIMARY_USE_CASE,
	      CURR_FY_QRTR.SECONDARY_USE_CASES,
	      CURR_FY_QRTR.PRODUCT_FAMILY,
	      CURR_FY_QRTR.PRODUCT_FAMILY_SUBTYPE_NAME,
	      CURR_FY_QRTR.PRODUCT_CATEGORY,
	      CURR_FY_QRTR.SUB_RENEWAL,
	      CURR_FY_QRTR.SUPPOSED_TO_BE_SUB_RENEWAL,
          SPLIT_CONFIG.NO_OF_SPLITS,
          SPLIT_CONFIG.SPLIT_ARR,
          SPLIT_CONFIG.SPLIT_ARR_RANK,
          SPLIT_CONFIG.SPLT_RANK_INDEX,
          ROW_NUMBER() OVER(PARTITION BY CURR_FY_QRTR.TRANSACTION_ID,CURR_FY_QRTR.TRANSACTION_LINE_ID ORDER BY SPLIT_CONFIG.SPLT_RANK_INDEX ASC) AS RN
      FROM "PRD_INFO_MART_OTC"."TRANSACTION_ARB_CALC" CURR_FY_QRTR
      LEFT JOIN CTE_SPLIT_ARR_ROW SPLIT_CONFIG ON (NVL(CURR_FY_QRTR.ROUNDED_LEGACY_TERMS_MONTHS,1) = SPLIT_CONFIG.INP_NUMBER)
      LEFT JOIN "PRD_INFO_MART_DIM"."ACCOUNT_DIM" ACCOUNT_DIM ON (CURR_FY_QRTR.OPP_ACCOUNT_ID = ACCOUNT_DIM.SF_ACCOUNT_ID)
      WHERE 1=1
      AND ARB_FLAG='Y'
      AND CURR_FY_QRTR.TRANSACTION_TYPE IN ('Invoice','Credit Memo')
      AND CURR_FY_QRTR.CHART_OF_ACCOUNT_FULL_NAME IS NOT NULL
      AND CURR_FY_QRTR.CHART_OF_ACCOUNT_FULL_NAME <> ''
      AND CURR_FY_QRTR.TRANS_SF_OPPORTUNITY IS NOT NULL
      AND CURR_FY_QRTR.TRANS_SF_OPPORTUNITY <> ''
  ) CURR_FY_QRTR
  WHERE 1=1
)
SELECT
      FISCAL_YEAR                                       AS FISCAL_YEAR_TRANSACTION,
      FISCAL_QUARTER                                    AS FISCAL_QUARTER_TRANSACTION,
      FISCAL_QUARTER_START_DATE                         AS FISCAL_QUARTER_START_DATE_TRANSACTION,
      FISCAL_QUARTER_END_DATE                           AS FISCAL_QUARTER_END_DATE_TRANSACTION,
      FISCAL_YEAR_SPLIT                                 AS FISCAL_YEAR,
      FISCAL_QUARTER_SPLIT                              AS FISCAL_QUARTER,
      FISCAL_QUARTER_START_DATE_SPLIT                   AS FISCAL_QUARTER_START_DATE,
      FISCAL_QUARTER_END_DATE_SPLIT                     AS FISCAL_QUARTER_END_DATE,
      TRANSACTION_ID                                    AS TRANSACTION_ID,
      TRANSACTION_LINE_ID                               AS TRANSACTION_LINE_ID,
      PO_NUMBER                                         AS PO_NUMBER,
      TRANDATE                                          AS TRANDATE,
      TRANSACTION_TYPE                                  AS TRANSACTION_TYPE,
      TRANS_SF_OPPORTUNITY                              AS TRANS_SF_OPPORTUNITY,
      OPP_ACCOUNT_ID                                    AS OPP_ACCOUNT_ID,
      NAME                                              AS NAME,
      INDUSTRY                                          AS INDUSTRY,
      INDUSTRY_NEW                                      AS INDUSTRY_NEW,
      ACCOUNT_GEO                                       AS ACCOUNT_GEO,
      ACCOUNT_SEGMENT                                   AS ACCOUNT_SEGMENT,
      ITEM_KEY                                          AS ITEM_KEY,
      PRODUCT_KEY                                       AS PRODUCT_KEY,
      ITEM_ID                                           AS ITEM_ID,
      SFDC_PRODUCT_ID                                   AS SFDC_PRODUCT_ID,
      SUBTYPE                                           AS SUBTYPE,
      TYPE_NAME                                         AS TYPE_NAME,
      SAAS_PRODUCT_FAMILY                               AS SAAS_PRODUCT_FAMILY,
      ITEM_FULL_NAME                                    AS ITEM_FULL_NAME, 
	  ITEM_SALES_DESCRIPTION                            AS ITEM_SALES_DESCRIPTION,
	  PRIMARY_USE_CASE                                  AS PRIMARY_USE_CASE,
	  SECONDARY_USE_CASES                               AS SECONDARY_USE_CASES,
	  PRODUCT_FAMILY                                    AS PRODUCT_FAMILY,
	  PRODUCT_FAMILY_SUBTYPE_NAME                       AS PRODUCT_FAMILY_SUBTYPE_NAME,
	  PRODUCT_CATEGORY                                  AS PRODUCT_CATEGORY,
	  SUB_RENEWAL                                       AS SUB_RENEWAL,
	  SUPPOSED_TO_BE_SUB_RENEWAL                        AS SUPPOSED_TO_BE_SUB_RENEWAL,
      LEGACY_TERM_START_DATE                            AS LEGACY_TERM_START_DATE,
      LEGACY_TERM_END_DATE                              AS LEGACY_TERM_END_DATE,
      AMOUNT_FOREIGN                                    AS AMOUNT_FOREIGN,
      ROUNDED_LEGACY_TERMS_MONTHS                       AS ROUNDED_LEGACY_TERMS_MONTHS,
      ROUNDED_LEGACY_TERMS_QUARTERS                     AS ROUNDED_LEGACY_TERMS_QUARTERS,
      SW_PERCENT                                        AS SW_PERCENT,
      NEW_AMOUNT                                        AS NEW_AMOUNT,
      MULTI_YEAR                                        AS MULTI_YEAR,
      NO_OF_SPLITS                                      AS NO_OF_SPLITS,
      ARB_AMOUNT_UPDATED                                AS ARB_AMOUNT,
      ANNIVERSARY_FLAG                                  AS ANNIVERSARY_FLAG 
FROM
CTE_SPLIT_ARR_FY_QTR
WHERE 1=1
;



